name: ce114_ce117_sdp_project
description: Pizza food delivery app.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.5.0
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.2.1
  geocode: ^1.0.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_sign_in: ^5.4.2
  lottie: ^1.4.3
  page_transition: ^2.0.9
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  razorpay_flutter: ^1.3.2
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "animation/1024.png"

flutter:
  assets:
    - animation/
  uses-material-design: true